drop table if exists public.download_events;
drop table if exists public.download_tokens;
drop table if exists public.downloads;
drop view if exists public.lead_consent_status;
drop table if exists public.consents;
drop table if exists public.leads;
drop table if exists public.consent_texts;
drop trigger if exists products_publication_rules on public.products;
drop function if exists app.check_product_publication();
drop trigger if exists product_prices_guard on public.product_prices;
drop trigger if exists product_files_guard on public.product_files;
drop function if exists app.guard_product_children();
drop function if exists app.product_is_draft(uuid);
drop function if exists app.product_of_version(uuid);
drop function if exists app.min_price_for(char, char, text);
drop function if exists app.current_price(uuid);
drop table if exists public.price_rule_exceptions;
drop table if exists public.product_prices;
drop table if exists public.product_files;
alter table if exists public.products drop constraint if exists products_current_version_fk;
drop table if exists public.product_versions;
drop table if exists public.products;
drop table if exists public.price_rules;
drop table if exists public.settings;
